---
title: "GitHub Tutorial 1"
author: "Sahar Mozaffari"
date: 2017-07-27
output: html_document

---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

First we need to make a github account here: www.github.com

```{r gitconfig, eval=FALSE}
$ git config --global user.name <firstname lastname>
$ git config --global user.email <youremail@domain>
$ git config --global core.editor <editor> 
```
Some possible core editors: emacs, vim, nano


Now go onto the Desktop and make a directory called planets
```{r gitconfig1, eval=FALSE}
$ cd Desktop
$ mkdir thesis
```




<!-- Insert the session information into the document -->
```{r session-info, eval=FALSE}
## Session information
```
